//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThemePark.Api.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThemePark.Api.Tests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:1,&quot;name&quot;:&quot;Twirly Ride&quot;,&quot;locationId&quot;:2,&quot;locationName&quot;:&quot;Fantasy&quot;},{&quot;id&quot;:2,&quot;name&quot;:&quot;Mine car Coaster&quot;,&quot;locationId&quot;:5,&quot;locationName&quot;:&quot;Western&quot;},{&quot;id&quot;:3,&quot;name&quot;:&quot;Haunted House&quot;,&quot;locationId&quot;:3,&quot;locationName&quot;:&quot;Horror&quot;},{&quot;id&quot;:4,&quot;name&quot;:&quot;Dragon Ride&quot;,&quot;locationId&quot;:2,&quot;locationName&quot;:&quot;Fantasy&quot;},{&quot;id&quot;:5,&quot;name&quot;:&quot;Gift Shop&quot;,&quot;locationId&quot;:1,&quot;locationName&quot;:&quot;General&quot;},{&quot;id&quot;:6,&quot;name&quot;:&quot;Space Ride&quot;,&quot;locationId&quot;:4,&quot;locationName&quot;:&quot;Sci/Fi&quot;},{&quot;id&quot;:7,&quot;name&quot;:&quot;Shootout at OK Corral/Lazer Tag&quot;,&quot;locationId&quot;:5,&quot;locationName&quot;:&quot;Western&quot;} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedAttractionData {
            get {
                return ResourceManager.GetString("ExpectedAttractionData", resourceCulture);
            }
        }
    }
}
